# Generated by Django 5.2.4 on 2025-08-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('distancia', models.FloatField()),
                ('duracion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='gestorRutas.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='gestorRutas.municipio')),
                ('ruta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='gestorRutas.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(null=True)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recuerdos', to='gestorRutas.departamento')),
                ('ruta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestorRutas.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.BinaryField()),
                ('tipo', models.CharField(default='image/png', max_length=100)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestorRutas.destino')),
                ('recuerdo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestorRutas.recuerdo')),
                ('ruta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestorRutas.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='gestorRutas.usuario'),
        ),
    ]
